export const fullData = [{
        id: 1,
        type: "vip",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
        },
    },
    {
        id: 2,
        type: "regular",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
            7: false,
            8: false,
        },
    },
    {
        id: 3,
        type: "vip",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
        },
    },{
        id: 4,
        type: "vip",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
        },
    },
    {
        id: 5,
        type: "vip",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
        },
    },
    {
        id: 6,
        type: "vip",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
        },
    },{
        id: 7,
        type: "Regular",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
            7: false,
            8: false,
        },
    },
    {
        id: 8,
        type: "Regular",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
            7: false,
            8: false,
        },
    },
    {
        id: 9,
        type: "Regular",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
            7: false,
            8: false,
        },
    },
    {
        id: 10,
        type: "Regular",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
            7: false,
            8: false,
        },
    },
    {
        id: 11,
        type: "Regular",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
            7: false,
            8: false,
        },
    },
    {
        id: 12,
        type: "Regular",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
            7: false,
            8: false,
        },
    },
    {
        id: 13,
        type: "Regular",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
            7: false,
            8: false,
        },
    },
    {
        id: 14,
        type: "Regular",
        seat: {
            1: false,
            2: false,
            3: false,
            4: false,
            5: false,
            6: false,
            7: false,
            8: false,
        },
    },
]




const dummy = [{
    table: "10",
    type: "vip",
    seat: [2,3,4,5]
}]
